name: lobby
version: '1.1-SNAPSHOT'
main: de.lobby.LobbySystemMain
api-version: '1.21'
description: Ein einfaches 1vs1-Duell-Plugin mit Queue und Lobby
commands:
  duel:
    description: Tritt einem 1vs1 bei
    usage: /duel
  leave:
    description: Verlasse die Warteschlange
    usage: /leave
  setupduel:
    description: Gibt das Duel-Setup-Tool
    usage: /setupduel
    permission: onevsone.setup
  reloadsettings:
    description: Lädt die Konfiguration neu
    usage: /reloadsettings
    permission: onevsone.admin

permissions:
  onevsone.setup:
    description: Zugriff auf Setup
    default: op
  onevsone.admin:
    description: Zugriff auf Admin-Befehle
    default: op