name: lobby
version: '1.1-SNAPSHOT'
main: de.lobby.LobbySystemMain
api-version: '1.21'
description: Ein einfaches 1vs1-Duell-Plugin mit Queue und Lobby
commands:
  duel:
    description: Tritt der 1vs1-Warteschlange bei
    usage: /duel
    permission: onevsone.duel
  leave:
    description: Verlasse die Warteschlange für ein Duell
    usage: /leave
  reload:
    description: Reloadet das Plugin
    usage: /<command>
  setupduel:
    description: Setup für Duel-Spawns
    usage: /setupduel

permissions:
  onevsone.duel:
    description: Erlaubt den Beitritt zur 1vs1-Queue
    default: true